### ISSUE TITLE
mailer broken with rails 3

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#101]
the approach to mailers seems to have changed in rails 3 and I think the current mailer code is broken

http://guides.rubyonrails.org/v3.2.9/action_mailer_basics.html

**Comment by balmas** [comment]
(fyi, I'm working on this right now -- should have something that minimally works soon)

**Comment by ryanfb** [comment]
Thanks for taking this on - I just figured we had borked some mail delivery settings (or the config/handshaking for it) on the papyri.info dev/prodo servers.
