### ISSUE TITLE
error displaying usage stats for other users 

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#103]
A change in usage_stats.haml to use @current_user instead of the @users array broke the display for any except the current user (e.g. when viewing stats for other users)

Also the publications links are going to the wrong controller - users controller instead of publications.

**Comment by hcayless** [comment]
Bah. Was trying to fix a related problem in a hurry and obviously half-assed it. I’ll fix it.

**Comment by balmas** [comment]
ah fixed already :) see #104
