### ISSUE TITLE
Lock HGV validation to EpiDoc 8.13

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#114]

**Comment by ryanfb** [comment]
Some files are still invalid under 8.13, but probably need to be hand-corrected:

* [HGV_meta_EpiDoc](https://gist.github.com/9f09d4c250e8f69c455e)
* [HGV_trans_EpiDoc](https://gist.github.com/a56f3a1fd2ca33475e3e) - from a random sampling, these seem to all be e.g. '`:`' in `@resp`, and pre-date SoSOL

Found with e.g.:

    find HGV_trans_EpiDoc -name '*.xml'|parallel -X -j8 -u "java -jar ~/source/dc3/sosol/lib/java/jing.jar ~/mess/current/8.13/tei-epidoc.rng {}" &> ~/mess/current/hgv_trans_epidoc_813_invalid.txt

**Comment by hcayless** [comment]
Random sampling show some of those are just invalid anyway: things like
empty lists (<list/>), or this beauty:

<origDate notAfter="-0257-02-29">
                        <offset type="before" n="1">vor</offset> 29. Febr.
257 v.Chr.</origDate>

I don't think that's a proper leap year. Nor does the ISO.

**Comment by ryanfb** [comment]
Looking closer at instances of `/0\d{3}-02-29/` in HGV_meta_EpiDoc, I see four instances of Feb. 29 on a non-leap-year come from `@type=mentioned`.

Three of these are all of the same class:

 * http://papyri.info/hgv/695
 * http://papyri.info/hgv/698
 * http://papyri.info/hgv/699

These are all of the form "Year 28, Audnaios 25" in the text. The conversion of this date into Feb. 29, 257   also happens in [*A Guide to the Zenon Archive*](https://books.google.com/books?id=hOg3AAAAIAAJ&pg=PA265&lpg=PA265&dq=year+28,+Audnaios+25&source=bl&ots=vsu4zzmxGr&sig=Yk4WyjyE7IQJa44zqjF48EwyNsc&hl=en&sa=X&ved=0CCAQ6AEwAGoVChMImrrut86wyAIVATw-Ch0OSg2u#v=onepage&q=year%2028%2C%20Audnaios%2025&f=false). 

The fourth (non-Zenon) instance of this is in [P.Tebt. 1 24](http://papyri.info/hgv/3660).

What say you, @jcowey @jds15?

**Comment by ryanfb** [comment]
After reading entirely too much about calendars (see e.g. https://en.wikipedia.org/wiki/Julian_calendar#Leap_year_error), manual testing has confirmed that the schema validator apparently avoids this entire issue by considering all BCE leap days invalid.

**Comment by hcayless** [comment]
I think we may actually be in Hell. So, the W3C changed their dateTime
specification in 2012: http://www.w3.org/TR/xmlschema11-2/#dateTime. The
latest one has a year zero, and specifies how to handle BCE leap years.
This means the actual correct date in ISO 8601 format is -0256-02-29. This,
however, fails to validate, because RelaxNG references the *old* XML Schema
Datatypes definition and the software that implements it faithfully
implements the busted definition. The (corrected) ISO date validates with
an XML Schema, but not with a RelaxNG schema. I don't think there even is a
maintainer of the RelaxNG standard anymore...I can ask around.

**Comment by ryanfb** [comment]
Ah, I had a brief panic about the possible BCE fencepost error when I looked at ISO 8601, but looking at TEI [`att.datable.w3c`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.w3c.html) (which is what I assumed the EpiDoc RNG inherited from, and spot checking that seems to be the case) it says it follows ["W3C XML Schema Part 2: Datatypes Second Edition"](http://www.w3.org/TR/xmlschema-2/) which has [deviations from ISO 8601](http://www.w3.org/TR/xmlschema-2/#deviantformats) for no year zero. Since TEI specs that, I don't think it's affected by the 2012 W3C update yet? If that's the case I think the current RNG is correct.

**Comment by ryanfb** [comment]
Also, previous discussion on this topic seems to exist if you [search MARKUP]( http://lsv.uky.edu/scripts/wa.exe?S1=markup) for "Use of 29 February in BCE dates" or "proposed EpiDoc guidelines parag. 7.3" in subject (unfortunately I can't find a way to link to search results or a complete discussion thread).

**Comment by ryanfb** [comment]
Tracing down where it gets registered as an error in the latest version of Jing it's in its XSD `DateTimeDatatype` use of Java's `GregorianCalendar#isLeapYear()`, which [expects BCE years to be negative and start at year 0](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/util/GregorianCalendar.java#L793-L800), and ignores the BC `Calendar.ERA` set by Jing: https://github.com/relaxng/jing-trang/blob/3309ae62e28b9a185cd2c85ec62fe6b4c0bfadd2/mod/xsd-datatype/src/main/com/thaiopensource/datatype/xsd/DateTimeDatatype.java#L255

So, how to actually handle it *correctly* (in Jing) depends on whether Jing's XSD implementation is targeting XSD 1.0 Second Edition or 1.1. It's claimed [here](http://www.thaiopensource.com/relaxng/jing-datatypes.html) that it's following 1.0 Second Edition (see also relaxng/jing-trang#192), so I think we're good to go and I can just patch/pullreq Jing to correctly validate our current usage of BCE leap years.

**Comment by ryanfb** [comment]
Continuing the pain (when will it end?), the following documents treat 300**CE** as a leap year:

 * https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV45/44882zr.xml
 * https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV45/44882zt.xml
 * https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV45/44882zu.xml

Which, by the logic of the proleptic Gregorian calendar, is not a leap year because it is divisible by 100 but not by 400. Thus these get flagged as invalid (both versions of XSD assume the proleptic Gregorian calendar, and Jing assumes it as well).

[@jcowey indicates here that HGV may be assuming the proleptic Julian calendar](http://lsv.uky.edu/scripts/wa.exe?A2=ind1009&L=MARKUP&P=R5892&I=-3), in which case…should we specify [`@calendar="#Julian"`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.html) (and then somehow, tortuously, eventually, correctly validate that)?

**Comment by hcayless** [comment]
Perhaps when we die…

I’m afraid the answer is "no". @calendar specifies the calendar being used in the content of the date element. @when is always and only proleptic Gregorian.

**Comment by ryanfb** [comment]
Searching further turned up the good ol' [EpiDoc guidelines suggestions for `origDate`](http://www.stoa.org/epidoc/gl/latest/supp-historigdate.html) stating to use `@when-custom` and `@datingMethod="#julian"`, which validates. Whether we want to convert HGV to this across-the-board might be another question.

**Comment by jds15** [comment]
Gack. Can you imagine a potential two-step solution to this?

(1) tie it off now with a kind of hack, just to stop the bleed
(2) in time figure out the more rigorous solution

?



On 10/8/15 4:22 PM, Ryan Baumann wrote:
>
> Searching further turned up the good ol' EpiDoc guidelines suggestions 
> for |origDate| 
> <http://www.stoa.org/epidoc/gl/latest/supp-historigdate.html> stating 
> to use |@when-custom| and |@datingMethod="#julian"|, which validates. 
> Whether we want to convert HGV to this across-the-board might be 
> another question.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sosol/sosol/issues/114#issuecomment-146675199>.
>

-- 
Associate Professor, Classical Studies, Duke University
Duke Collaboratory for Classics Computing
Greek, Roman and Byzantine Studies
Duke Data Bank of Documentary Papyri

www.duke.edu/~jds15

**Comment by jcowey** [comment]
I intend to look at the implications of trying to fix this properly. With ```@when-custom``` and ```datingMethod="#julian"``` etc. We also need the addition of authority tags to HGV files. ```div type="figure"``` has to move to facsimile. Making the relevant changes on the dev files and then tweaking the editor on dev, testing. Once OK merging into production (would entail relevant PN changes having been made on dev first I reckon). Some sort of hack seems half baked and a lot of trouble. Might as well do it properly.

**Comment by hcayless** [comment]
I think Ryan has done #1: patched the RNG validator so that it can deal with pre-XSD 1.1 (i.e. no year 0) proleptic Gregorian dates. We can use that patched version for validation. That will work for validation in papyri.info. We *might* be able to get the maintainers to accept the patch even.

There are two avenues for a more rigorous solution:

1) switch to @date-custom (probably easiest); with or without @datingMethod="#julian". We could define our own dating method to be proleptic Gregorian without year zero. I’m assuming that is actually the dating system at work in @when now, and not Julian, where the leap years are a nightmare?

2) Actually fix the problem. This is a nightmare of conflicting standards bodies and standards that aren’t going to be willing to revise anything. I am going to have to try to do something about it in my capacity as Mayor of the Village of the DamnedChair of the TEI Council. I’d advise against #2 unless you’re feeling particularly quixotic.

**Comment by jds15** [comment]
yes, avoiding the nightmare (2) is what i was trying to urge!

On 10/9/15 7:55 AM, Hugh A. Cayless wrote:
> I think Ryan has done #1: patched the RNG validator so that it can 
> deal with pre-XSD 1.1 (i.e. no year 0) proleptic Gregorian dates. We 
> can use that patched version for validation. That will work for 
> validation in papyri.info. We *might* be able to get the maintainers 
> to accept the patch even.
>
> There are two avenues for a more rigorous solution:
>
> 1) switch to @date-custom (probably easiest); with or without 
> @datingMethod="#julian". We could define our own dating method to be 
> proleptic Gregorian without year zero. I’m assuming that is actually 
> the dating system at work in @when now, and not Julian, where the leap 
> years are a nightmare?
>
> 2) Actually fix the problem. This is a nightmare of conflicting 
> standards bodies and standards that aren’t going to be willing to 
> revise anything. I am going to have to try to do something about it in 
> my capacity as Mayor of the Village of the DamnedChair of the TEI 
> Council. I’d advise against #2 unless you’re feeling particularly 
> quixotic.
>
> > On Oct 9, 2015, at 6:35 , jds15 <notifications@github.com> wrote:
> >
> > Gack. Can you imagine a potential two-step solution to this?
> >
> > (1) tie it off now with a kind of hack, just to stop the bleed
> > (2) in time figure out the more rigorous solution
> >
> > ?
> >
> >
> >
> > On 10/8/15 4:22 PM, Ryan Baumann wrote:
> > >
> > > Searching further turned up the good ol' EpiDoc guidelines 
> suggestions
> > > for |origDate|
> > > <http://www.stoa.org/epidoc/gl/latest/supp-historigdate.html> stating
> > > to use |@when-custom| and |@datingMethod="#julian"|, which validates.
> > > Whether we want to convert HGV to this across-the-board might be
> > > another question.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sosol/sosol/issues/114#issuecomment-146675199>.
> > >
> >
> > --
> > Associate Professor, Classical Studies, Duke University
> > Duke Collaboratory for Classics Computing
> > Greek, Roman and Byzantine Studies
> > Duke Data Bank of Documentary Papyri
> >
> > www.duke.edu/~jds15
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/sosol/sosol/issues/114#issuecomment-146830231>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sosol/sosol/issues/114#issuecomment-146842477>.
>

-- 
Associate Professor, Classical Studies, Duke University
Duke Collaboratory for Classics Computing
Greek, Roman and Byzantine Studies
Duke Data Bank of Documentary Papyri

www.duke.edu/~jds15

**Comment by jcowey** [comment]
feeling in no way "quixotic" but still looking to provide solution which lets us "continue to" or "go back to" validating with "latest" RNG schema

**Comment by hcayless** [comment]
I meant @when-custom rather than @date-custom of course.

**Comment by jcowey** [comment]
basically following what Ryan had already mentioned:
[EpiDoc Guidelines for origDate](http://www.stoa.org/epidoc/gl/latest/supp-historigdate.html)

**Comment by ryanfb** [comment]
One thing that's been in the back of my mind for switching to `@when-custom` has been making the corresponding change to indexing/search so that it gets handled correctly there (so it doesn't simply fall off as being detected as a year for date range searches).

Re: proleptic Julian leap year nightmares, Wikipedia sez "The determination of leap years in the proleptic Julian calendar (in either numbering) is distinct from the question of which years were historically considered leap years during the Roman era, due to the so-called leap year error". The question is what system we're using (or: what system someone had in mind when converting from an ancient/astronomical date), and being explicit about that in the encoding. If we say we're using the proleptic Gregorian calendar universally, for example, we would need to switch those Feb. 29 300CE dates to Mar. 1 300CE. Note however that for BCE dates down to the day, the gap between proleptic Julian and proleptic Gregorian gets wide and confusing quickly, so if e.g. Feb. 29 257BCE Julian proleptic was assumed that's actually something like Feb. 25 257BCE Gregorian proleptic (I think, but could be wrong).
