### ISSUE TITLE
force encoding to UTF-8 on data coming from MediaWiki

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#130]
Reported by @PietroLiuzzo

Rails 3 bug fixes for utf-8 encoding were overlooked in the ingest of data from MediaWiki.

http://sosol.perseids.org/sosol/cts_publications/create_from_agent?agent=http://www.eagle-network.eu&id=q10353&filter=q10353$9df24e93-40de-e4ac-4997-5b830fecb17e

corrupts the encoding

**Comment by balmas** [comment]
we need to upgrade to a newer version of the jruby json gem for this:

See https://github.com/flori/json/issues/101

**Comment by ryanfb** [comment]
Cleaning up old issues - this looks like it should be fixed everywhere now (`master` also has `gem 'json', '>=1.6.6'` in `Gemfile`).
