### ISSUE TITLE
Grit:repo:log reports unicode chars in author name as hexadecimal

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#164]
when this falls through to the show_commits display, the author_name in the commit hash has hexadecimal chars in it causing an incompatibility error.  The easy solution is to force_encoding("UTF-8") on the display of the author name. The right solution is probably to force_encoding on the data at the point it comes back from the grit log.   It could also be that using jgit instead of grit for the log will solve this. Another reason, along with #105, to try to get the remove_grit branch deployed?

**Comment by ryanfb** [comment]
We finally got a round of dev testing in with the remove_git branch merged, and the only Git-related issue that came up seems to be #161. So that seems promising.

**Comment by ryanfb** [comment]
Since `remove_grit` (#81) is now in production, this shouldn't be an issue anymore.
