### ISSUE TITLE
org.eclipse.jgit.internal.storage.file.FileRepository memory leak

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#167]
```
369 instances of "org.eclipse.jgit.internal.storage.file.FileRepository", loaded by "org.apache.catalina.loader.WebappClassLoader @ 0x704d11400" occupy 3,658,976,296 (86.05%) bytes. These instances are referenced from one instance of "org.jruby.runtime.builtin.IRubyObject[]", loaded by "org.apache.catalina.loader.WebappClassLoader @ 0x704d11400"
```

Used by `@jgit_repo` inside the `Repository` model. We might be better off explicitly initializing and closing `jgit_repo` within the blocks that need it (i.e. call `.close()` after we're done and then assign the variable `nil` to encourage GC).

**Comment by hcayless** [comment]
FileRepository claims to be threadsafe, so creating a cache that will allow its contents to be garbage collected is feasible. That should be very easy to do, then we'd just have to make jgit_repo call cache.get(repo_path). Might be better than creating and destroying the FileRepository every time it's needed.

**Comment by ryanfb** [comment]
I've done some work for this on [the `jgit_repo` branch](https://github.com/sosol/sosol/tree/jgit_repo). Passes all tests locally. The changed interface should be amenable to dropping in some sort of cache (Java-native like WeakHashMap or JCS?), instead of always recreating every time, if it's too much of a performance penalty. The idea behind using an instance attribute in the first place was to cache the JGit `FileRepository` creation and let the GC handle it when `Repository` instances went out of use, but apparently we have to be more careful than that. I don't think the recreation penalty is really all that bad, though, and hopefully it fixes the more immediate memory leak problem.

**Comment by hcayless** [comment]
:-D take a look at the [cache_jgit_repo](https://github.com/sosol/sosol/tree/cache_jgit_repo) branch. It swaps out the call to jgit_repo with a cached version using a WeakHashMap. Worth a try I think.

**Comment by ryanfb** [comment]
Frankly that's less confusing than my jgit_repo method which yields to a block. I'll go ahead and drop this in and we'll see how it goes!

**Comment by ryanfb** [comment]
The `cache_jgit_repo` branch is now live from tag [`papyri.20160420.cache_jgit_repo`](https://github.com/sosol/sosol/releases/tag/papyri.20160420.cache_jgit_repo). If all goes well I'll merge that back to `master` and close this issue.
