### ISSUE TITLE
HTTPS for RPX/Janrain callback URLs

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#245]
Since browsers are getting more strict about sending form data across non-HTTPS connections, and we're starting to add HTTPS on production, it might be good to default to HTTPS for the SoSOL callback URLs used for RPX login.

Should be do-able by passing `:protocol => 'https'` to `url_for` wherever an `auth_info` call is happening in `app/controllers/rpx_controller.rb`.

We probably want to make this an environment-configurable option so that it doesn't trip up non-HTTPS environments.

See also: #42

**Comment by hcayless** [comment]
I think it would be reasonable to just push all editor traffic to HTTPS in production on papyri.info. I don't want to require it for the PN though.

**Comment by ryanfb** [comment]
Fixed by 95b32e19d8317d9105b5d34a75701d7054bb1039
