### ISSUE TITLE
Support Demotic (egy-Egyd) for edition divs

### ISSUE THREAD

**Issue by jcowey** [sosol/sosol#254]
In https://github.com/papyri/xsugar/blob/master/epidoc.xsg#L107

instead of 
TEXTLANGLIST = ((ara)|(grc)|(la)|(la-Grek)|(grc-Latn)|(cop))
can we please have 
TEXTLANGLIST = ((ara)|(grc)|(la)|(la-Grek)|(grc-Latn)|(cop)|(egy-Egyd))

This will allow users to declare the div to be Demotic. At present the work around is to declare it as `grc` and then change to `egy-Egyd` with a `<foreign>` tag

e.g.
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.dime/o.dime.1/o.dime.1.86.xml
```
         <div xml:lang="grc" type="edition" xml:space="preserve">
<ab>
<lb n="1"/><foreign xml:lang="egy-Egyd">
```

This is not how it should be.

**Comment by jcowey** [comment]
For the lang name `egy-Egyd`
see
http://www.stoa.org/epidoc/gl/latest/supp-language.html

**Comment by ryanfb** [comment]
Should now be live for papyri.info - if there are any issues, please reopen and let me know.

**Comment by jcowey** [comment]
Thanks. Just worked very nicely for me.
