### ISSUE TITLE
Withdraw submission broken

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#302]
Reported by @jcowey. Goes to the withdraw confirmation screen, but the actual "withdraw" request results in a 404, likely resulting from changes in Rails defaults for PUT/POST routing across the upgrades from Rails 3 to Rails 6.

**Comment by jcowey** [comment]
https://papyri.info/editor/publications/100634/withdraw

Did not work for me

**Comment by jcowey** [comment]
And file still on the DDbDP Board:

![Bildschirmfoto 2022-04-07 um 22 12 29](https://user-images.githubusercontent.com/612992/162288179-bff78780-1766-482b-a3fe-017c9875cdf5.png)

If you like to try taking that file @ryanfb, making yourself finalizer and testing it, then please go ahead.

**Comment by jcowey** [comment]
Got it to work today!!

**Comment by ryanfb** [comment]
Glad to hear it's working now - yes, just going to the `withdraw` URL won't work, as that will still result in a `GET` request. I've just changed the withdraw confirmation screen to use a `POST` request instead when you click the button, so you still have to go through the whole withdraw flow to make it work. Please let me know if there are any further issues.
