### ISSUE TITLE
ability to display terms of service

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#54]
For https://github.com/perseids-project/perseids_docs/issues/254 

Add a versionable terms of service display, and a permanent link to the current terms of service.

We want to display the terms of service and require the user to accept them before continuing, but once accepted, not display again unless explicitly requested, or a new version of the terms has been deployed.

**Comment by balmas** [comment]
@ryanfb @hcayless @paregorios I would be very happy to have your feedback on what I'm implementing in the perseus_shibboleth branch (and will hopefully soon update for use with rails3 in our ongoing work on that).  The changes can be found here:

https://github.com/sosol/sosol/compare/perseus_shibboleth...sosol:accept_terms

It includes

* a site-wide configuration setting to set the version of the terms
* adding a new accept_terms field in the users table to record the version of the terms last accepted
* a new before_filter to show terms if the user's accepted terms version is less than than the current version. (Skipped for api calls)

What I want to change before deploying in the rails3 branch, or at least before requesting the perseus rails3 branch be merged into master is to make it possible for the terms text to be site specific. I'm not sure the best way to do this, and it might be something that's better off waiting for other changes coming next year, I'm not sure.  

But anyway, I'd be happy to have your thoughts on any of this.

**Comment by ryanfb** [comment]
Can we also put the terms text in a `Sosol::Application.config` variable, and render that out in `app/views/user/_terms_text.haml`? This would allow per-site/install terms configs outside of version control in e.g. the `config/environments/*_secret.rb` files. The partial could just dump the string with `html_safe`, so that the text could have HTML styling/formatting elements.

**Comment by balmas** [comment]
Yes that's a good idea. I will make that change in the implementation in the rails3 branch. Thanks!.
