### ISSUE TITLE
identifier.set_content should rails error if commit returns nil?

### ISSUE THREAD

**Issue by balmas** [sosol/sosol#56]
currently identifier.set_content leaves it up to the calling code to check for nils on the commit_sha and and handle as an error condition. Most places in the application don't check on this right now. I think it might be better to raise an error here so that we can inform the user that something went wrong.

**Comment by ryanfb** [comment]
Agreed. Probably we should re-raise any caught error in Repository#commit_content after logging, instead of returning nil there. Then a rescue in any controller action that calls set_content/set_xml_content, and puts it in error flash with the appropriate redirect?

**Comment by balmas** [comment]
sounds about right :)

**Comment by balmas** [comment]
burned a bit by this one today -- ran out of inodes on our filesystem and commits were failing but the UI was happily saying saves were successful.  I'll assign myself to this to implement.
