### ISSUE TITLE
Need test repo for CITE/CTS/OAC identifiers/files

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#63]
@balmas - I've been doing work on integrating `rails-3-perseus-merge` on the `rails-3-perseus-merge-dc3` branch, and trying to get tests to pass. Part of the issue is I don't have a test repo with CITE/CTS/OAC files to test against, so I've worked around this for now by using `config.site_identifiers` and wrapping the tests in a guard checking to see if the related identifier is configured (so you could override this and have the tests run in your local test environment by setting `config.site_identifiers` in `config/environments/test_secret.rb`).

Grepping for `PATH_PREFIX` in `app/models`, these seem to be the directories we need:

* `CITE_ALIGNMENT_XML`
* `CITE_COMMENTARY_XML`
* `CITE_OA_JSON`
* `CITE_OA_XML`
* `CITE_TREEBANK_XML`
* `CTS_XML_CITATIONS`
* `CTS_XML_EpiDoc`
* `CTS_XML_TEI`
* `CTS_XML_TextInventory`
* `XML_OAC`

If you could fork [ryanfb/idp.data.test](https://github.com/ryanfb/idp.data.test) and add these directories with sample files used for the automated tests in their expected paths, I can look at using that for comprehensive SoSOL testing.

**Comment by balmas** [comment]
I've been working on that this week!

In the rails-3-perseus-merge branch I've defined a new rake test:perseids and these do all pass right now, but the setup is still a wip.

I've been working through a docker instance setup of everything and need to update the image on docker hub still

The data data can almost all be found in 
https://github.com/PerseusDL/perseids_canonical_test.git canonical.git

But I'll go ahead and fork your test repo add it there too

**Comment by ryanfb** [comment]
Ah ok - I tried using GitHub search to code-search for some of those path strings figuring I might be able to find an existing repo that way, but couldn't turn it up. Thanks!
