### ISSUE TITLE
Submit occasionally goes straight to false "committed" state

### ISSUE THREAD

**Issue by ryanfb** [sosol/sosol#73]
If a user tries to resubmit, this also results in the same text being "committed" within 2-3 minutes of itself. 

Some instances of this bug may be caught by 1e9149962ab12dee6d66851ea0beddf4d5a413da.

**Comment by ryanfb** [comment]
This may be sometimes happening because a failed submit action causes identifiers to go into an inconsistent "submitted" state (instead of "editing"), which causes them to skip all boards in the next submit. Should wrap identifier status changes within submit inside the same transaction.

**Comment by balmas** [comment]
Just identified another way this can happen.
Precondition, publication has been submitted to the only (or last) applicable board for it.
If the user backs up and resubmits the Submit form, the controller will send it to publication.submit_to_next_board (via publication.submit) and the lookup of submittable_identifiers will come up empty, and thus the lookup of board_identifiers will also be empty.  On line 258, the test for the length of board_identifiers > 0 will fail, and the fall-through behavior is to act as if the publication is ready to be committted. The board copy will stay where it is, but the user's original copy gets set to status of "committed".

**Comment by ryanfb** [comment]
How exactly does that happen? With b905eeb5352e9418186ed425b4195be6dce7a6e2, the whole `PublicaitonsController#submit` action should be in an exclusive lock. So if a user goes back and gets a cached overview page where they can still hit the "Submit" button, that should trigger a second `PublicaitonsController#submit` which has to wait for the first lock to release, and once the first `PublicaitonsController#submit` finishes and releases the lock, the status should already be changed and the action should immediately bail and redirect from: https://github.com/sosol/sosol/blob/master/app/controllers/publications_controller.rb#L221-L225

In the process of working through that though, I realized the problem is it could still race because we load the `@publication` variable without an exclusive lock in `PublicationsController#find_publication` - so we either need to add `@publication.reload` inside `PublicationsController#submit`'s lock before the status check, or pass `:lock => true` to `Publication.find` in `PublicationsController#find_publication`. Does that sound right, and like it would fix this case?

**Comment by balmas** [comment]
Ah, you're right lines 221-225  should prevent this from happening normally.  I noticed it while working on an new API call for submitting publications in which I overlooked that check, thinking it was specific to user-interaction.  I think your additional suggestion sounds good, although I wonder if this should be managed by strongly by the model class and not depending upon good controller behavior? That would be a bigger change though because we would need to distinguish between the various "submitted" states a publication can be in.

**Comment by ryanfb** [comment]
I added a test + lock in the [`submit_lock` branch on my fork](https://github.com/ryanfb/sosol/tree/submit_lock), which I'll probably merge back tomorrow.

I think there are a few places (definitely in submit) where we should move some logic from the controller into the model. This would also make it easier to interact with things on an interactive Rails console.

**Comment by ryanfb** [comment]
Experimenting with finding existing cases for this issue:

    false_committed = Publication.where(:status => 'committed').select{|p| (p.is_community_publication? == false) && (p.id == p.origin.id) && (p.children.length == 0)}

None (for papyri.info) when I then do:

    false_new = false_committed.select{|p| p.updated_at.year == 2016}

So it doesn't seem to be continuing to happen. Just a lot of cleanup left for where it already happened.

**Comment by ryanfb** [comment]
See also: papyri/sosol#60
